import { useEffect, useState } from "react";

export default function Operations({ apiUrl }) {
  const [token] = useState(() => localStorage.getItem("farmer-token") || "");
  const [inventory, setInventory] = useState([]);
  const [economics, setEconomics] = useState(null);
  const [item, setItem] = useState({ name: "", quantity: "", unit: "kg", reorderAt: "", cost: "" });
  const [expense, setExpense] = useState({ title: "", category: "Fertilizer", amount: "" });
  const [notice, setNotice] = useState("");
  const headers = { "Content-Type": "application/json", Authorization: `Bearer ${token}` };
  const load = async () => {
    if (!token) return;
    const [inventoryResponse, economicsResponse] = await Promise.all([fetch(`${apiUrl}/api/inventory`, { headers }), fetch(`${apiUrl}/api/economics`, { headers })]);
    if (inventoryResponse.ok) setInventory(await inventoryResponse.json());
    if (economicsResponse.ok) setEconomics(await economicsResponse.json());
  };
  useEffect(() => { load(); }, [token]);
  const addItem = async (event) => { event.preventDefault(); const response = await fetch(`${apiUrl}/api/inventory`, { method: "POST", headers, body: JSON.stringify(item) }); const data = await response.json(); if (!response.ok) return setNotice(data.error); setInventory((previous) => [data, ...previous]); setItem({ name: "", quantity: "", unit: "kg", reorderAt: "", cost: "" }); setNotice("Inventory item saved."); };
  const addExpense = async (event) => { event.preventDefault(); const response = await fetch(`${apiUrl}/api/economics/expenses`, { method: "POST", headers, body: JSON.stringify(expense) }); const data = await response.json(); if (!response.ok) return setNotice(data.error); setExpense({ title: "", category: "Fertilizer", amount: "" }); setNotice("Expense saved."); load(); };
  const adjust = async (entry, amount) => { const response = await fetch(`${apiUrl}/api/inventory/${entry.id}`, { method: "PATCH", headers, body: JSON.stringify({ quantity: Math.max(0, entry.quantity + amount) }) }); if (response.ok) { const updated = await response.json(); setInventory((previous) => previous.map((row) => row.id === updated.id ? updated : row)); } };
  if (!token) return <section className="operations"><p className="eyebrow">FARM OPERATIONS</p><h2>Sign in to manage inventory and expenses.</h2><p className="section-copy">Your records are tied to your farmer account and stored locally by the project backend.</p></section>;
  return <section className="operations" id="operations"><div className="phase-heading"><p className="eyebrow">FARM OPERATIONS</p><h2>Track farm inputs, stock alerts, and costs.</h2><p>Inventory and expenses are saved to your farmer profile. Low stock is flagged against the reorder amount you set.</p></div><div className="operations-grid"><article className="panel inventory-card"><div className="card-title"><h3>Inventory</h3><span>{inventory.length} items</span></div>{inventory.length ? <div className="inventory-list">{inventory.map((entry) => <div key={entry.id} className={entry.quantity <= entry.reorderAt ? "low-stock" : ""}><div><b>{entry.name}</b><small>{entry.category} · ₹{entry.cost || 0}</small></div><span><button onClick={() => adjust(entry, -1)}>−</button><b>{entry.quantity} {entry.unit}</b><button onClick={() => adjust(entry, 1)}>+</button></span></div>)}</div> : <div className="empty">Add seed, fertilizer, pesticide, or equipment stock.</div>}<form onSubmit={addItem} className="compact-form"><input required placeholder="Item name" value={item.name} onChange={(event) => setItem({ ...item, name: event.target.value })} /><div><input required type="number" min="0" placeholder="Quantity" value={item.quantity} onChange={(event) => setItem({ ...item, quantity: event.target.value })} /><input type="number" min="0" placeholder="Low-stock at" value={item.reorderAt} onChange={(event) => setItem({ ...item, reorderAt: event.target.value })} /></div><button>Add inventory</button></form></article><article className="panel expense-card"><div className="card-title"><h3>Farm expenses</h3><b>₹{economics?.spent?.toLocaleString() || 0}</b></div><p>Total recorded input spend</p><form onSubmit={addExpense} className="compact-form"><input required placeholder="Expense title" value={expense.title} onChange={(event) => setExpense({ ...expense, title: event.target.value })} /><select value={expense.category} onChange={(event) => setExpense({ ...expense, category: event.target.value })}><option>Fertilizer</option><option>Seed</option><option>Labour</option><option>Irrigation</option><option>Other</option></select><input required type="number" min="1" placeholder="Amount in rupees" value={expense.amount} onChange={(event) => setExpense({ ...expense, amount: event.target.value })} /><button>Add expense</button></form>{economics?.expenses?.length ? <ul className="expense-list">{economics.expenses.slice(0, 3).map((row) => <li key={row.id}><span>{row.title}<small>{row.category}</small></span><b>₹{row.amount.toLocaleString()}</b></li>)}</ul> : <div className="empty">No expenses recorded yet.</div>}</article></div>{notice && <p className="operations-notice">{notice}</p>}</section>;
}
